# permissions for end users to view clusterissues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterissue-viewer-role
rules:
- apiGroups:
  - zora.undistro.io
  resources:
  - clusterissues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zora.undistro.io
  resources:
  - clusterissues/status
  verbs:
  - get
