name: Build and Push Docker Images
on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    env:
      REPO: "registry.undistro.io"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.17"
      - name: Show Go version
        run: go version
      - name: Get dependencies
        run: go mod download

      - name: Registry login
        env:
          LOGIN: "${{ secrets.REGISTRY_USERNAME }}"
          PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"
        run: echo $PASSWORD | docker login --username $LOGIN --password-stdin $REPO

      - name: Show version tag
        run: |
          echo "Tag: $GITHUB_REF_NAME"

      - name: Build operator
        run: IMG=$REPO/library/zora-operator:$GITHUB_REF_NAME make docker-build
      - name: Build server
        run: IMG=$REPO/library/zora-server:$GITHUB_REF_NAME DOCKERFILE=Dockerfile.server make docker-build
      - name: Build worker
        run: IMG=$REPO/library/zora-worker:$GITHUB_REF_NAME DOCKERFILE=Dockerfile.worker make docker-build

      - name: Push operator
        run: docker push $REPO/library/zora-operator:$GITHUB_REF_NAME
      - name: Push server
        run: docker push $REPO/library/zora-server:$GITHUB_REF_NAME
      - name: Push worker
        run: docker push $REPO/library/zora-worker:$GITHUB_REF_NAME

      - name: Registry logout
        run: docker logout
